### ISSUE TITLE
Constant writes to errors.log

### ISSUE THREAD

**Issue by deathtrip** [xxxserxxx/gotop#85] opened 2020-03-24 16:57 UTC
##### gotop version:
3.5.0
##### OS/Arch:
Arch Linux, using AUR gotop package compiled with go-pie
##### Terminal emulator: 
Terminator

gotop constantly writes to `~/.local/state/gotop/errors.log` , it looks like this:

> 17:33:24 mem.go:41:   updating Main to {12564205568 4472352768 35.59598530758455}
17:33:24 mem.go:41:   updating Swap to {4294963200 0 0}
17:33:25 mem.go:41:   updating Main to {12564205568 4472463360 35.596865522409125}
17:33:25 mem.go:41:   updating Swap to {4294963200 0 0}
17:33:26 mem.go:41:   updating Main to {12564205568 4473417728 35.60446145033975}
17:33:26 mem.go:41:   updating Swap to {4294963200 0 0}

> 

and so on...
always repeating lines about changing memory and swap values
it's not as bad as #49, but still it's two lines every second

**Comment by xxxserxxx** [comment] 2020-04-05 12:42
@deathtrip Explained in #86, and confirmed that this is PEBCAK on my end.  The next minor release will resolve this.

You reported first but I answered the other first, so closing this as a duplicate of #86

**Closed by xxxserxxx** 2020-04-05 12:42 UTC
